version: '2'
services:
  ruby_server:
    build:
      context: ./
    volumes:
      - ./config.yml:/var/www/inferno/config.yml
      - ./data:/var/www/inferno/data
  validator_service:
    image: infernocommunity/fhir-validator-service:v0.1.1
    environment:
      DISABLE_TX: 'true'
  nginx_server:
    image: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4567:80"
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - ruby_server
